A Couple Display Enhancements
oliver-ni/poketwo pull request #126
Opened 2021-01-20 20:12 UTC by michaelsong4399

**Main Changes**
1. Display more information during `p!release`.
Added :sparkles:, IV.
Added "Can't find/release (x) Pokemon" message.
2. Require text confirmation (instead of y/n) during `p!release`.
Thank you Sk#4676 for the two suggestions above!
3. Display rarity for rare pokemons in dex.
Thank you Yiqii#6383 for the suggestion above!

**Stylistic Changes**
1. Display custom server prefixes in `p!favoriteall` support message.
Thank you corpsesimp#3949 for the suggestion above!

2021-01-21 22:04 UTC, oliver-ni commented
> 2\. Require text confirmation (instead of y/n) during `p!release`.
>     Thank you Sk#4676 for the two suggestions above!

I don't think i like this behavior.

The other things look fine.

2021-01-22 04:32 UTC, pikaninja commented
> > 2. Require text confirmation (instead of y/n) during `p!release`.
> > Thank you Sk#4676 for the two suggestions above!
> 
> I don't think i like this behavior.
> 
> The other things look fine.
thing about this is people might accidently release a mon if they're not paying attention and this would force them to think a little more

2021-01-22 05:10 UTC, oliver-ni commented
> thing about this is people might accidently release a mon if they're not paying attention and this would force them to think a little more

y/n is sufficient. The pokémon getting released are already listed. the # on releaseall is because it's very easy to mess up a mass release and you can't see which pokémon are being released.

2021-01-28 09:01 UTC, oliver-ni requested changes

2021-01-28 09:01 UTC, oliver-ni commented on cogs/pokemon.py
> +                f'Are you sure you want to **release** your{" ✨" if mons[0].shiny else ""} Level {mons[0].level} {mons[0].iv_percentage * 100:.2f}% {mons[0].species}. No. {mons[0].idx} for 2 pc? [y/N
We can use string formatting to replace this stuff, would probably be better
look around in the auction / market code for examples, I think

2021-01-28 09:01 UTC, oliver-ni commented on cogs/pokemon.py
> +                f'{"✨ " if x.shiny else ""}Level {x.level} {x.iv_percentage * 100:.2f}% {x.species} ({x.idx})' for x in mons
Same here

2021-01-29 21:47 UTC, oliver-ni commented
Looks good, thank you!

2021-01-29 21:47 UTC, merged